name: getfit
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_ui_auth: ^1.10.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  pdf: ^3.10.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
